import { useState, useEffect, useRef, useCallback } from 'react';
import { useBlocker } from 'react-router-dom';
import type { AIUsage, Position, Candidate, InterviewResult, EvaluationDimension } from '@/types';
import { EvaluationDimensionCard } from './EvaluationDimensionCard';
import { ExportButtons } from './ExportButtons';
import { Card, CardHeader, CardBody, Input, Textarea, Select, Button } from '@/components/ui';
import { useAI } from '@/hooks/useAI';
import { usePositionStore } from '@/store/positionStore';
import { useSettingsStore } from '@/store/settingsStore';
import { getPreferredResumeText } from '@/utils/resume';
import { autofillWintalentEvaluationDraft, isWintalentInterviewLink } from '@/api/wintalent';
import { getInjectedGenerationGuidancePrompt } from '@/lib/generationMemory';
import { reportError, trackEvent, usageFromAIUsage } from '@/lib/analytics';

const AUTO_SAVE_DELAY = 2000; // 2 seconds debounce

/**
 * Strip volatile metadata (aiUsage) from an InterviewResult so that
 * content-only comparison between draft and final is accurate.
 */
const stripVolatileFields = (r: InterviewResult): Omit<InterviewResult, 'aiUsage'> => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { aiUsage, ...content } = r;
  return content;
};

// Convert date to local datetime string for input (YYYY-MM-DD HH:mm)
const toLocalDateTimeString = (date: Date): string => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
};

interface SummaryEditorProps {
  position: Position;
  candidate: Candidate;
  autoGenerate?: boolean;
}

const defaultResult: InterviewResult = {
  interview_info: {
    interviewer: '',
    overall_result: '待定',
    interview_time: toLocalDateTimeString(new Date()),
  },
  evaluation_dimensions: [
    { dimension: '专业能力', score: 3, assessment_points: '' },
    { dimension: '通用素质', score: 3, assessment_points: '' },
    { dimension: '适配度', score: 3, assessment_points: '' },
    { dimension: '管理能力', score: 3, assessment_points: '' },
  ],
  summary: {
    suggested_level: '',
    comprehensive_score: 3,
    overall_comment: '',
    interview_conclusion: '待定',
    is_strongly_recommended: false,
  },
};

export const SummaryEditor: React.FC<SummaryEditorProps> = ({
  position,
  candidate,
  autoGenerate = false,
}) => {
  const {
    isLoading: aiLoading,
    ensureGenerationMemoryFresh,
    generateInterviewSummary,
    analyzeInterviewSummaryRewrite,
  } = useAI();
  const { setInterviewResult, completeInterview, updateCandidate, recordFeedbackEvent } = usePositionStore();
  const { feishuUser, aiModel } = useSettingsStore();
  const preferredResumeText = getPreferredResumeText(candidate);

  const buildInitialResult = useCallback(
    (): InterviewResult =>
      candidate.interviewResult || {
        ...defaultResult,
        interview_info: {
          ...defaultResult.interview_info,
          interview_time: candidate.interviewTime
            ? toLocalDateTimeString(new Date(candidate.interviewTime))
            : defaultResult.interview_info.interview_time,
        },
      },
    [candidate.interviewResult, candidate.interviewTime]
  );

  const [result, setResult] = useState<InterviewResult>(buildInitialResult);
  const [strengths, setStrengths] = useState<string[]>(candidate.interviewResult?.additional_info?.strengths || []);
  const [concerns, setConcerns] = useState<string[]>(candidate.interviewResult?.additional_info?.concerns || []);
  const [followUps, setFollowUps] = useState<string[]>(candidate.interviewResult?.additional_info?.follow_up_questions || []);
  const [summaryUsage, setSummaryUsage] = useState<AIUsage | undefined>(
    candidate.interviewResult?.aiUsage?.summaryGeneration
  );
  const [summaryMemoryRefreshUsage, setSummaryMemoryRefreshUsage] = useState<AIUsage | undefined>(undefined);
  const [summaryMemoryRefreshStatus, setSummaryMemoryRefreshStatus] = useState<string | null>(null);
  const [wintalentAutofillLoading, setWintalentAutofillLoading] = useState(false);
  const [wintalentAutofillError, setWintalentAutofillError] = useState<string | null>(null);

  const [saveStatus, setSaveStatus] = useState<'saved' | 'saving' | 'unsaved'>('saved');
  const autoSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const rewriteAnalysisTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const lastRewriteSignatureRef = useRef<string>('');
  const isInitialMountRef = useRef(true);
  const hasAutoGeneratedRef = useRef(false);
  const hasUserEditedSinceGenerationRef = useRef(false);

  const handleGenerateSummary = useCallback(async () => {
    const startedAt = Date.now();
    setSummaryMemoryRefreshStatus('正在更新岗位面评记忆...');
    const memoryRefreshResult = await ensureGenerationMemoryFresh(position.id, 'summary_generation');
    if (memoryRefreshResult.refreshed) {
      setSummaryMemoryRefreshUsage(memoryRefreshResult.usage);
      setSummaryMemoryRefreshStatus(null);
    } else if (memoryRefreshResult.error) {
      setSummaryMemoryRefreshStatus(`岗位面评记忆刷新失败：${memoryRefreshResult.error}，继续使用当前指引。`);
    } else {
      setSummaryMemoryRefreshStatus(null);
    }
    const refreshedPosition = usePositionStore.getState().getPosition(position.id) || position;
    const summaryGuidance = getInjectedGenerationGuidancePrompt(refreshedPosition, 'summary_generation');
    const generatedResult = await generateInterviewSummary(
      candidate.questions,
      position.description || '',
      preferredResumeText,
      candidate.name,
      position.title,
      candidate.quickNotes,
      candidate.meetingNotesContext,
      candidate.codingChallenges,
      summaryGuidance
    );

    if (generatedResult) {
      setResult({
        ...generatedResult.data,
        aiUsage: {
          ...candidate.interviewResult?.aiUsage,
          summaryGeneration: generatedResult.usage,
        },
      });
      setStrengths(generatedResult.data.additional_info?.strengths || []);
      setConcerns(generatedResult.data.additional_info?.concerns || []);
      setFollowUps(generatedResult.data.additional_info?.follow_up_questions || []);
      setSummaryUsage(generatedResult.usage);

      const finalResult: InterviewResult = {
        ...generatedResult.data,
        additional_info: {
          strengths: generatedResult.data.additional_info?.strengths || [],
          concerns: generatedResult.data.additional_info?.concerns || [],
          follow_up_questions: generatedResult.data.additional_info?.follow_up_questions || [],
        },
        aiUsage: {
          ...candidate.interviewResult?.aiUsage,
          summaryGeneration: generatedResult.usage,
        },
      };

      setSaveStatus('saving');
      setInterviewResult(position.id, candidate.id, finalResult);
      updateCandidate(position.id, candidate.id, {
        lastGeneratedSummaryDraft: generatedResult.data,
      });
      hasUserEditedSinceGenerationRef.current = false;
      setSaveStatus('saved');
      if (summaryGuidance?.trim()) {
        trackEvent({
          eventName: 'guidance_applied_to_summary_generation',
          feature: 'feedback_guidance',
          success: true,
          model: aiModel,
          details: {
            positionId: position.id,
            candidateId: candidate.id,
          },
        });
      }
      trackEvent({
        eventName: 'summary_generation_succeeded',
        feature: 'summary_generation',
        success: true,
        durationMs: Date.now() - startedAt,
        model: aiModel,
        ...usageFromAIUsage(generatedResult.usage),
        details: {
          guidanceApplied: Boolean(summaryGuidance?.trim()),
        },
      });
      return;
    }

    trackEvent({
      eventName: 'summary_generation_failed',
      feature: 'summary_generation',
      success: false,
      durationMs: Date.now() - startedAt,
      model: aiModel,
      errorCode: 'empty_summary_result',
    });
    reportError({
      error: 'AI summary generation returned empty result',
      feature: 'summary_generation',
      errorCategory: 'ai',
      durationMs: Date.now() - startedAt,
      model: aiModel,
      requestContext: {
        endpoint: '/api/ai/chat/completions',
        method: 'POST',
        provider: 'openai-compatible',
        model: aiModel,
        operation: 'generate_summary',
      },
      reproContext: {
        route: window.location.pathname,
        positionId: position.id,
        candidateId: candidate.id,
        candidateStatus: candidate.status,
      },
      inputSnapshot: {
        candidateName: candidate.name,
        positionTitle: position.title,
        questionCount: candidate.questions.length,
      },
    });
  }, [
    aiModel,
    candidate.codingChallenges,
    candidate.id,
    candidate.interviewResult?.aiUsage,
    candidate.status,
    candidate.meetingNotesContext,
    candidate.name,
    candidate.questions,
    candidate.quickNotes,
    ensureGenerationMemoryFresh,
    generateInterviewSummary,
    preferredResumeText,
    position,
    setInterviewResult,
    updateCandidate,
  ]);

  useEffect(() => {
    isInitialMountRef.current = true;
    hasAutoGeneratedRef.current = false;
    hasUserEditedSinceGenerationRef.current = false;
    lastRewriteSignatureRef.current = '';
    setResult(
      candidate.interviewResult || {
        ...defaultResult,
        interview_info: {
          ...defaultResult.interview_info,
          interview_time: candidate.interviewTime
            ? toLocalDateTimeString(new Date(candidate.interviewTime))
            : defaultResult.interview_info.interview_time,
        },
      }
    );
    setStrengths(candidate.interviewResult?.additional_info?.strengths || []);
    setConcerns(candidate.interviewResult?.additional_info?.concerns || []);
    setFollowUps(candidate.interviewResult?.additional_info?.follow_up_questions || []);
    setSummaryUsage(candidate.interviewResult?.aiUsage?.summaryGeneration);
    setSaveStatus('saved');
  }, [candidate.id, candidate.interviewResult, candidate.interviewTime]);

  useEffect(() => {
    lastRewriteSignatureRef.current = '';
    hasUserEditedSinceGenerationRef.current = false;
  }, [candidate.id, candidate.lastGeneratedSummaryDraft]);

  // Auto-fill interviewer name if logged in and field is empty
  useEffect(() => {
    if (feishuUser?.name && !result.interview_info.interviewer) {
      setResult((prev) => ({
        ...prev,
        interview_info: { ...prev.interview_info, interviewer: feishuUser.name },
      }));
    }
  }, [feishuUser?.name, result.interview_info.interviewer]);

  // Build the final result object
  const buildFinalResult = useCallback((): InterviewResult => ({
    ...result,
    additional_info: {
      strengths,
      concerns,
      follow_up_questions: followUps,
    },
  }), [result, strengths, concerns, followUps]);

  // Save draft function
  const handleSaveDraft = useCallback(() => {
    setSaveStatus('saving');
    const finalResult = buildFinalResult();
    setInterviewResult(position.id, candidate.id, finalResult);
    setSaveStatus('saved');
  }, [buildFinalResult, position.id, candidate.id, setInterviewResult]);

  // Fire rewrite analysis immediately (fire-and-forget).
  // Returns true if analysis was triggered, false if skipped (no meaningful edits).
  const fireRewriteAnalysis = useCallback(() => {
    if (!candidate.lastGeneratedSummaryDraft || !hasUserEditedSinceGenerationRef.current) {
      return false;
    }

    const finalResult = buildFinalResult();
    const draftContent = stripVolatileFields(candidate.lastGeneratedSummaryDraft);
    const finalContent = stripVolatileFields(finalResult);
    const draftJson = JSON.stringify(draftContent);
    const finalJson = JSON.stringify(finalContent);
    if (draftJson === finalJson) {
      return false;
    }

    const lengthDiffRatio = Math.abs(finalJson.length - draftJson.length) / Math.max(draftJson.length, 1);
    const draft = candidate.lastGeneratedSummaryDraft;
    const structuralFieldChanged =
      draft.interview_info?.overall_result !== finalResult.interview_info?.overall_result ||
      draft.summary?.comprehensive_score !== finalResult.summary?.comprehensive_score ||
      draft.summary?.interview_conclusion !== finalResult.summary?.interview_conclusion;
    if (lengthDiffRatio < 0.05 && !structuralFieldChanged) {
      return false;
    }

    const signature = JSON.stringify({ draft: draftContent, final: finalContent });
    if (signature === lastRewriteSignatureRef.current) {
      return false;
    }

    // Fire immediately (no timer)
    void (async () => {
      const insight = await analyzeInterviewSummaryRewrite(
        candidate.lastGeneratedSummaryDraft as InterviewResult,
        finalResult
      );
      if (!insight) {
        return;
      }
      lastRewriteSignatureRef.current = signature;
      const preferences = insight.data.preferences.length
        ? insight.data.preferences
        : ['保持结构化输出'];
      recordFeedbackEvent(position.id, {
        type: 'summary_rewritten',
        candidateId: candidate.id,
        details: {
          preferences,
          rewriteIntensity: insight.data.rewriteIntensity,
        },
      });
    })();
    return true;
  }, [
    analyzeInterviewSummaryRewrite,
    buildFinalResult,
    candidate.id,
    candidate.lastGeneratedSummaryDraft,
    position.id,
    recordFeedbackEvent,
  ]);

  // Flush all pending timers and save immediately
  const flushPendingSaves = useCallback(() => {
    if (autoSaveTimerRef.current) {
      clearTimeout(autoSaveTimerRef.current);
      autoSaveTimerRef.current = null;
    }
    if (rewriteAnalysisTimerRef.current) {
      clearTimeout(rewriteAnalysisTimerRef.current);
      rewriteAnalysisTimerRef.current = null;
      fireRewriteAnalysis();
    }
    handleSaveDraft();
  }, [fireRewriteAnalysis, handleSaveDraft]);

  // Complete interview function
  const handleComplete = useCallback(() => {
    // Flush any pending rewrite analysis before completing
    if (rewriteAnalysisTimerRef.current) {
      clearTimeout(rewriteAnalysisTimerRef.current);
      rewriteAnalysisTimerRef.current = null;
      fireRewriteAnalysis();
    }
    if (autoSaveTimerRef.current) {
      clearTimeout(autoSaveTimerRef.current);
      autoSaveTimerRef.current = null;
    }
    setSaveStatus('saving');
    const finalResult = buildFinalResult();
    completeInterview(position.id, candidate.id, finalResult);
    setSaveStatus('saved');
  }, [buildFinalResult, position.id, candidate.id, completeInterview, fireRewriteAnalysis]);

  // Auto-save with debounce on user edits
  useEffect(() => {
    // Skip on initial mount
    if (isInitialMountRef.current) {
      isInitialMountRef.current = false;
      return;
    }

    // Clear existing timer
    if (autoSaveTimerRef.current) {
      clearTimeout(autoSaveTimerRef.current);
    }

    // Mark as unsaved
    setSaveStatus('unsaved');
    hasUserEditedSinceGenerationRef.current = true;

    // Set new timer
    autoSaveTimerRef.current = setTimeout(() => {
      handleSaveDraft();
    }, AUTO_SAVE_DELAY);

    return () => {
      if (autoSaveTimerRef.current) {
        clearTimeout(autoSaveTimerRef.current);
      }
    };
  }, [concerns, followUps, handleSaveDraft, result, strengths]);

  // Debounced rewrite analysis (15s after edits stabilize)
  useEffect(() => {
    if (!candidate.lastGeneratedSummaryDraft || !hasUserEditedSinceGenerationRef.current) {
      return;
    }

    const finalResult = buildFinalResult();
    const draftContent = stripVolatileFields(candidate.lastGeneratedSummaryDraft);
    const finalContent = stripVolatileFields(finalResult);
    const draftJson = JSON.stringify(draftContent);
    const finalJson = JSON.stringify(finalContent);
    if (draftJson === finalJson) {
      return;
    }

    const lengthDiffRatio = Math.abs(finalJson.length - draftJson.length) / Math.max(draftJson.length, 1);
    const draft = candidate.lastGeneratedSummaryDraft;
    const structuralFieldChanged =
      draft.interview_info?.overall_result !== finalResult.interview_info?.overall_result ||
      draft.summary?.comprehensive_score !== finalResult.summary?.comprehensive_score ||
      draft.summary?.interview_conclusion !== finalResult.summary?.interview_conclusion;
    if (lengthDiffRatio < 0.05 && !structuralFieldChanged) {
      return;
    }

    const signature = JSON.stringify({ draft: draftContent, final: finalContent });
    if (signature === lastRewriteSignatureRef.current) {
      return;
    }

    if (rewriteAnalysisTimerRef.current) {
      clearTimeout(rewriteAnalysisTimerRef.current);
    }

    rewriteAnalysisTimerRef.current = setTimeout(() => {
      fireRewriteAnalysis();
    }, 15000);

    return () => {
      if (rewriteAnalysisTimerRef.current) {
        clearTimeout(rewriteAnalysisTimerRef.current);
      }
    };
  }, [
    buildFinalResult,
    candidate.lastGeneratedSummaryDraft,
    concerns,
    fireRewriteAnalysis,
    followUps,
    result,
    strengths,
  ]);

  // Auto-generate summary on mount if requested and no existing result
  useEffect(() => {
    if (
      autoGenerate &&
      !hasAutoGeneratedRef.current &&
      !candidate.interviewResult &&
      position.description &&
      preferredResumeText
    ) {
      hasAutoGeneratedRef.current = true;
      void handleGenerateSummary();
    }
  }, [
    autoGenerate,
    candidate.interviewResult,
    candidate.codingChallenges,
    candidate.meetingNotesContext,
    candidate.name,
    candidate.questions,
    candidate.quickNotes,
    preferredResumeText,
    position.description,
    position.id,
    position.title,
    aiModel,
    generateInterviewSummary,
    handleGenerateSummary,
    setInterviewResult,
  ]);

  // Block in-app navigation when there are unsaved changes
  const hasUnsavedChanges = saveStatus === 'unsaved';
  const blocker = useBlocker(hasUnsavedChanges);

  // Handle blocker state: flush saves and proceed, or show confirmation
  useEffect(() => {
    if (blocker.state !== 'blocked') {
      return;
    }
    // Auto-flush: save draft + fire rewrite analysis, then proceed
    flushPendingSaves();
    blocker.proceed();
  }, [blocker, flushPendingSaves]);

  // Warn on browser close/refresh when there are unsaved changes
  useEffect(() => {
    if (!hasUnsavedChanges) {
      return;
    }
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      // Flush auto-save synchronously (localStorage.setItem is sync)
      handleSaveDraft();
      e.preventDefault();
    };
    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
  }, [hasUnsavedChanges, handleSaveDraft]);

  // Flush pending rewrite analysis on component unmount (more reliable than beforeunload)
  useEffect(() => {
    return () => {
      if (rewriteAnalysisTimerRef.current) {
        clearTimeout(rewriteAnalysisTimerRef.current);
        rewriteAnalysisTimerRef.current = null;
      }
      fireRewriteAnalysis();
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const updateDimension = (index: number, updates: Partial<EvaluationDimension>) => {
    const newDimensions = [...result.evaluation_dimensions];
    newDimensions[index] = { ...newDimensions[index], ...updates };
    setResult({ ...result, evaluation_dimensions: newDimensions });
  };

  const addDimension = () => {
    setResult({
      ...result,
      evaluation_dimensions: [
        ...result.evaluation_dimensions,
        { dimension: '新维度', score: 3, assessment_points: '' },
      ],
    });
  };

  const removeDimension = (index: number) => {
    const newDimensions = result.evaluation_dimensions.filter((_, i) => i !== index);
    setResult({ ...result, evaluation_dimensions: newDimensions });
  };

  const resultOptions = [
    { value: '通过', label: '通过' },
    { value: '不通过', label: '不通过' },
    { value: '待定', label: '待定' },
  ];

  const scoreOptions = [
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
  ];

  const isCompleted = candidate.status === 'completed';
  const hasPageLink = Boolean(candidate.candidateLink);
  const canAutofillWintalent = isWintalentInterviewLink(candidate.candidateLink);
  const pendingSummaryEventCount = position.generationMemoryState?.pendingSummaryEventCount || 0;
  const pendingSummaryCandidateCount = position.generationMemoryState?.pendingSummaryCandidateCount || 0;
  const isSummaryMemoryDirty = position.generationMemoryState?.dirtyScopes.includes('summary_generation');

  const renderUsage = (usage: AIUsage | undefined, label: string) => {
    if (!usage) {
      return null;
    }

    return (
      <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-700">
        <span className="font-medium text-slate-800">{label}</span>
        <span className="ml-2">input {usage.input}</span>
        <span className="ml-2">cached {usage.cached}</span>
        <span className="ml-2">output {usage.output}</span>
      </div>
    );
  };

  const handleAutofillWintalent = useCallback(async () => {
    const candidateLink = candidate.candidateLink?.trim();
    if (!candidateLink || !isWintalentInterviewLink(candidateLink)) {
      setWintalentAutofillError('当前候选人没有可用的 Wintalent 面试链接。');
      return;
    }

    setWintalentAutofillLoading(true);
    setWintalentAutofillError(null);
    try {
      const finalResult = buildFinalResult();
      const response = await autofillWintalentEvaluationDraft(candidateLink, finalResult);
      window.open(response.evaluationUrl || response.candidateLinkUrl || candidateLink, '_blank', 'noopener,noreferrer');
    } catch (error) {
      setWintalentAutofillError(error instanceof Error ? error.message : '回填 Wintalent 评价页失败');
    } finally {
      setWintalentAutofillLoading(false);
    }
  }, [buildFinalResult, candidate.candidateLink]);

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h2 className="text-sm font-medium text-gray-900">
            面试结果：{candidate.name} - {position.title}
          </h2>
          {/* Completion status */}
          {isCompleted && (
            <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded">
              已完成
            </span>
          )}
          {/* Save status indicator */}
          <span className={`text-xs ${
            saveStatus === 'saved' ? 'text-green-600' :
            saveStatus === 'saving' ? 'text-yellow-600' :
            'text-gray-400'
          }`}>
            {saveStatus === 'saved' && '✓ 已保存'}
            {saveStatus === 'saving' && '...'}
            {saveStatus === 'unsaved' && '（未保存）'}
          </span>
          {isSummaryMemoryDirty && (
            <span className="text-xs text-amber-700">
              待合并事件 {pendingSummaryEventCount}，候选人 {pendingSummaryCandidateCount}
            </span>
          )}
        </div>

        <div className="flex gap-2">
          {canAutofillWintalent && (
            <Button
              variant="secondary"
              onClick={() => void handleAutofillWintalent()}
              isLoading={wintalentAutofillLoading}
            >
              一键回填到 Wintalent
            </Button>
          )}
          <Button
            variant="secondary"
            onClick={handleGenerateSummary}
            isLoading={aiLoading}
            disabled={!position.description || !preferredResumeText}
          >
            AI 生成总结
          </Button>
          {!isCompleted && (
            <Button onClick={handleComplete}>
              完成面试
            </Button>
          )}
        </div>
      </div>

      {hasPageLink && (
        <Card>
          <CardHeader>
            <h3 className="text-sm font-medium text-gray-700">候选人页面</h3>
          </CardHeader>
          <CardBody>
            <a
              href={candidate.candidateLink}
              target="_blank"
              rel="noreferrer"
              className="text-sm text-blue-600 hover:text-blue-800 break-all"
            >
              {candidate.candidateLink}
            </a>
          </CardBody>
        </Card>
      )}

      {summaryMemoryRefreshStatus && (
        <div className="rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-700">
          {summaryMemoryRefreshStatus}
        </div>
      )}
      {renderUsage(summaryMemoryRefreshUsage, '面评记忆更新 Token')}
      {renderUsage(summaryUsage, 'AI 总结生成 Token')}

      {wintalentAutofillError && (
        <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">
          {wintalentAutofillError}
        </div>
      )}

      {/* Interview Info */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-medium text-gray-700">面试信息</h3>
        </CardHeader>
        <CardBody>
          <div className="grid grid-cols-3 gap-3">
            <Input
              label="面试官"
              value={result.interview_info.interviewer}
              onChange={(e) =>
                setResult({
                  ...result,
                  interview_info: { ...result.interview_info, interviewer: e.target.value },
                })
              }
            />
            <Input
              label="时间"
              value={result.interview_info.interview_time}
              onChange={(e) =>
                setResult({
                  ...result,
                  interview_info: { ...result.interview_info, interview_time: e.target.value },
                })
              }
            />
            <Select
              label="总体结果"
              value={result.interview_info.overall_result}
              onChange={(e) =>
                setResult({
                  ...result,
                  interview_info: {
                    ...result.interview_info,
                    overall_result: e.target.value as '通过' | '不通过' | '待定',
                  },
                })
              }
              options={resultOptions}
            />
          </div>
        </CardBody>
      </Card>

      {/* Evaluation Dimensions */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-700">评估维度</h3>
            <Button variant="ghost" size="sm" onClick={addDimension}>
              + 添加维度
            </Button>
          </div>
        </CardHeader>
        <CardBody className="space-y-3">
          {result.evaluation_dimensions.map((dim, index) => (
            <EvaluationDimensionCard
              key={index}
              dimension={dim}
              onUpdate={(updates) => updateDimension(index, updates)}
              onRemove={() => removeDimension(index)}
              canRemove={result.evaluation_dimensions.length > 1}
            />
          ))}
        </CardBody>
      </Card>

      {/* Summary */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-medium text-gray-700">综合评价</h3>
        </CardHeader>
        <CardBody className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <Input
              label="建议级别"
              value={result.summary.suggested_level}
              onChange={(e) =>
                setResult({
                  ...result,
                  summary: { ...result.summary, suggested_level: e.target.value },
                })
              }
              placeholder="例如：H7、P6"
            />
            <Select
              label="综合评分"
              value={result.summary.comprehensive_score.toString()}
              onChange={(e) =>
                setResult({
                  ...result,
                  summary: { ...result.summary, comprehensive_score: parseInt(e.target.value) },
                })
              }
              options={scoreOptions}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <Select
              label="面试结论"
              value={result.summary.interview_conclusion}
              onChange={(e) =>
                setResult({
                  ...result,
                  summary: {
                    ...result.summary,
                    interview_conclusion: e.target.value as '通过' | '不通过' | '待定',
                  },
                })
              }
              options={resultOptions}
            />
            <div className="flex items-center pt-6">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={result.summary.is_strongly_recommended}
                  onChange={(e) =>
                    setResult({
                      ...result,
                      summary: {
                        ...result.summary,
                        is_strongly_recommended: e.target.checked,
                      },
                    })
                  }
                  className="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500"
                />
                <span className="text-sm text-gray-700">强烈推荐</span>
              </label>
            </div>
          </div>

          <Textarea
            label="总体评价"
            value={result.summary.overall_comment}
            onChange={(e) =>
              setResult({
                ...result,
                summary: { ...result.summary, overall_comment: e.target.value },
              })
            }
            autoResize
            placeholder="请输入对候选人的综合评价..."
          />
        </CardBody>
      </Card>

      {/* Additional Info */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-medium text-gray-700">补充信息（可选）</h3>
        </CardHeader>
        <CardBody className="space-y-3">
          <StringListInput
            label="优势"
            items={strengths}
            onChange={setStrengths}
          />
          <StringListInput
            label="顾虑"
            items={concerns}
            onChange={setConcerns}
          />
          <StringListInput
            label="后续跟进问题"
            items={followUps}
            onChange={setFollowUps}
          />
        </CardBody>
      </Card>

      {/* Export Buttons */}
      <Card>
        <CardBody className="flex justify-end gap-2">
          {canAutofillWintalent && (
            <Button
              variant="secondary"
              onClick={() => void handleAutofillWintalent()}
              isLoading={wintalentAutofillLoading}
            >
              一键回填到 Wintalent
            </Button>
          )}
          {!isCompleted && (
            <Button onClick={handleComplete}>
              完成面试
            </Button>
          )}
          <ExportButtons
            result={{
              ...result,
              additional_info: {
                strengths,
                concerns,
                follow_up_questions: followUps,
              },
            }}
            candidateName={candidate.name}
            positionTitle={position.title}
          />
        </CardBody>
      </Card>
    </div>
  );
};

// Helper component for string list input
const StringListInput: React.FC<{
  label: string;
  items: string[];
  onChange: (items: string[]) => void;
}> = ({ label, items, onChange }) => {
  const [newItem, setNewItem] = useState('');

  const handleAdd = () => {
    if (newItem.trim()) {
      onChange([...items, newItem.trim()]);
      setNewItem('');
    }
  };

  const handleRemove = (index: number) => {
    onChange(items.filter((_, i) => i !== index));
  };

  return (
    <div>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      <div className="space-y-1">
        {items.map((item, index) => (
          <div key={index} className="flex items-center gap-2">
            <span className="text-sm text-gray-600">• {item}</span>
            <button
              onClick={() => handleRemove(index)}
              className="text-gray-400 hover:text-red-500"
            >
              <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        ))}
        <div className="flex gap-2">
          <Input
            value={newItem}
            onChange={(e) => setNewItem(e.target.value)}
            placeholder={`添加${label}...`}
            onKeyPress={(e) => e.key === 'Enter' && handleAdd()}
          />
          <Button variant="ghost" size="sm" onClick={handleAdd} disabled={!newItem.trim()}>
            添加
          </Button>
        </div>
      </div>
    </div>
  );
};
