import { useState, useEffect, useRef, useCallback } from 'react';
import type { AIUsage, Position, Candidate, InterviewResult, EvaluationDimension } from '@/types';
import { EvaluationDimensionCard } from './EvaluationDimensionCard';
import { ExportButtons } from './ExportButtons';
import { Card, CardHeader, CardBody, Input, Textarea, Select, Button } from '@/components/ui';
import { useAI } from '@/hooks/useAI';
import { usePositionStore } from '@/store/positionStore';
import { useSettingsStore } from '@/store/settingsStore';
import { getPreferredResumeText } from '@/utils/resume';
import { trackEvent, usageFromAIUsage } from '@/lib/analytics';

const AUTO_SAVE_DELAY = 2000; // 2 seconds debounce

// Convert date to local datetime string for input (YYYY-MM-DD HH:mm)
const toLocalDateTimeString = (date: Date): string => {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
};

interface SummaryEditorProps {
  position: Position;
  candidate: Candidate;
  autoGenerate?: boolean;
}

const defaultResult: InterviewResult = {
  interview_info: {
    interviewer: '',
    overall_result: '待定',
    interview_time: toLocalDateTimeString(new Date()),
  },
  evaluation_dimensions: [
    { dimension: '专业能力', score: 3, assessment_points: '' },
    { dimension: '通用素质', score: 3, assessment_points: '' },
    { dimension: '适配度', score: 3, assessment_points: '' },
    { dimension: '管理能力', score: 3, assessment_points: '' },
  ],
  summary: {
    suggested_level: '',
    comprehensive_score: 3,
    overall_comment: '',
    interview_conclusion: '待定',
    is_strongly_recommended: false,
  },
};

export const SummaryEditor: React.FC<SummaryEditorProps> = ({
  position,
  candidate,
  autoGenerate = false,
}) => {
  const { isLoading: aiLoading, generateInterviewSummary } = useAI();
  const { setInterviewResult, completeInterview } = usePositionStore();
  const { feishuUser, aiModel } = useSettingsStore();
  const preferredResumeText = getPreferredResumeText(candidate);

  const buildInitialResult = useCallback(
    (): InterviewResult =>
      candidate.interviewResult || {
        ...defaultResult,
        interview_info: {
          ...defaultResult.interview_info,
          interview_time: candidate.interviewTime
            ? toLocalDateTimeString(new Date(candidate.interviewTime))
            : defaultResult.interview_info.interview_time,
        },
      },
    [candidate.interviewResult, candidate.interviewTime]
  );

  const [result, setResult] = useState<InterviewResult>(buildInitialResult);
  const [strengths, setStrengths] = useState<string[]>(candidate.interviewResult?.additional_info?.strengths || []);
  const [concerns, setConcerns] = useState<string[]>(candidate.interviewResult?.additional_info?.concerns || []);
  const [followUps, setFollowUps] = useState<string[]>(candidate.interviewResult?.additional_info?.follow_up_questions || []);
  const [summaryUsage, setSummaryUsage] = useState<AIUsage | undefined>(
    candidate.interviewResult?.aiUsage?.summaryGeneration
  );

  const [saveStatus, setSaveStatus] = useState<'saved' | 'saving' | 'unsaved'>('saved');
  const autoSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isInitialMountRef = useRef(true);
  const hasAutoGeneratedRef = useRef(false);

  const handleGenerateSummary = async () => {
    const startedAt = Date.now();
    const generatedResult = await generateInterviewSummary(
      candidate.questions,
      position.description || '',
      preferredResumeText,
      candidate.name,
      position.title,
      candidate.quickNotes,
      candidate.meetingNotesContext,
      candidate.codingChallenges
    );

    if (generatedResult) {
      setResult({
        ...generatedResult.data,
        aiUsage: {
          ...candidate.interviewResult?.aiUsage,
          summaryGeneration: generatedResult.usage,
        },
      });
      setStrengths(generatedResult.data.additional_info?.strengths || []);
      setConcerns(generatedResult.data.additional_info?.concerns || []);
      setFollowUps(generatedResult.data.additional_info?.follow_up_questions || []);
      setSummaryUsage(generatedResult.usage);

      const finalResult: InterviewResult = {
        ...generatedResult.data,
        additional_info: {
          strengths: generatedResult.data.additional_info?.strengths || [],
          concerns: generatedResult.data.additional_info?.concerns || [],
          follow_up_questions: generatedResult.data.additional_info?.follow_up_questions || [],
        },
        aiUsage: {
          ...candidate.interviewResult?.aiUsage,
          summaryGeneration: generatedResult.usage,
        },
      };

      setSaveStatus('saving');
      setInterviewResult(position.id, candidate.id, finalResult);
      setSaveStatus('saved');
      trackEvent({
        eventName: 'summary_generation_succeeded',
        feature: 'summary_generation',
        success: true,
        durationMs: Date.now() - startedAt,
        model: aiModel,
        ...usageFromAIUsage(generatedResult.usage),
      });
      return;
    }

    trackEvent({
      eventName: 'summary_generation_failed',
      feature: 'summary_generation',
      success: false,
      durationMs: Date.now() - startedAt,
      model: aiModel,
      errorCode: 'empty_summary_result',
    });
  };

  useEffect(() => {
    isInitialMountRef.current = true;
    hasAutoGeneratedRef.current = false;
    setResult(buildInitialResult());
    setStrengths(candidate.interviewResult?.additional_info?.strengths || []);
    setConcerns(candidate.interviewResult?.additional_info?.concerns || []);
    setFollowUps(candidate.interviewResult?.additional_info?.follow_up_questions || []);
    setSummaryUsage(candidate.interviewResult?.aiUsage?.summaryGeneration);
    setSaveStatus('saved');
  }, [buildInitialResult, candidate.id, candidate.interviewResult]);

  // Auto-fill interviewer name if logged in and field is empty
  useEffect(() => {
    if (feishuUser?.name && !result.interview_info.interviewer) {
      setResult((prev) => ({
        ...prev,
        interview_info: { ...prev.interview_info, interviewer: feishuUser.name },
      }));
    }
  }, [feishuUser?.name, result.interview_info.interviewer]);

  // Build the final result object
  const buildFinalResult = useCallback((): InterviewResult => ({
    ...result,
    additional_info: {
      strengths,
      concerns,
      follow_up_questions: followUps,
    },
  }), [result, strengths, concerns, followUps]);

  // Save draft function
  const handleSaveDraft = useCallback(() => {
    setSaveStatus('saving');
    const finalResult = buildFinalResult();
    setInterviewResult(position.id, candidate.id, finalResult);
    setSaveStatus('saved');
  }, [buildFinalResult, position.id, candidate.id, setInterviewResult]);

  // Complete interview function
  const handleComplete = useCallback(() => {
    setSaveStatus('saving');
    const finalResult = buildFinalResult();
    completeInterview(position.id, candidate.id, finalResult);
    setSaveStatus('saved');
  }, [buildFinalResult, position.id, candidate.id, completeInterview]);

  // Auto-save with debounce on user edits
  useEffect(() => {
    // Skip on initial mount
    if (isInitialMountRef.current) {
      isInitialMountRef.current = false;
      return;
    }

    // Clear existing timer
    if (autoSaveTimerRef.current) {
      clearTimeout(autoSaveTimerRef.current);
    }

    // Mark as unsaved
    setSaveStatus('unsaved');

    // Set new timer
    autoSaveTimerRef.current = setTimeout(() => {
      handleSaveDraft();
    }, AUTO_SAVE_DELAY);

    return () => {
      if (autoSaveTimerRef.current) {
        clearTimeout(autoSaveTimerRef.current);
      }
    };
  }, [concerns, followUps, handleSaveDraft, result, strengths]);

  // Auto-generate summary on mount if requested and no existing result
  useEffect(() => {
    if (
      autoGenerate &&
      !hasAutoGeneratedRef.current &&
      !candidate.interviewResult &&
      position.description &&
      preferredResumeText
    ) {
      hasAutoGeneratedRef.current = true;
      void handleGenerateSummary();
    }
  }, [
    autoGenerate,
    candidate.interviewResult,
    candidate.codingChallenges,
    candidate.meetingNotesContext,
    candidate.name,
    candidate.questions,
    candidate.quickNotes,
    preferredResumeText,
    position.description,
    position.id,
    position.title,
    aiModel,
    generateInterviewSummary,
    setInterviewResult,
  ]);

  const updateDimension = (index: number, updates: Partial<EvaluationDimension>) => {
    const newDimensions = [...result.evaluation_dimensions];
    newDimensions[index] = { ...newDimensions[index], ...updates };
    setResult({ ...result, evaluation_dimensions: newDimensions });
  };

  const addDimension = () => {
    setResult({
      ...result,
      evaluation_dimensions: [
        ...result.evaluation_dimensions,
        { dimension: '新维度', score: 3, assessment_points: '' },
      ],
    });
  };

  const removeDimension = (index: number) => {
    const newDimensions = result.evaluation_dimensions.filter((_, i) => i !== index);
    setResult({ ...result, evaluation_dimensions: newDimensions });
  };

  const resultOptions = [
    { value: '通过', label: '通过' },
    { value: '不通过', label: '不通过' },
    { value: '待定', label: '待定' },
  ];

  const scoreOptions = [
    { value: '1', label: '1' },
    { value: '2', label: '2' },
    { value: '3', label: '3' },
    { value: '4', label: '4' },
    { value: '5', label: '5' },
  ];

  const isCompleted = candidate.status === 'completed';
  const hasPageLink = Boolean(candidate.candidateLink);

  const renderUsage = (usage: AIUsage | undefined, label: string) => {
    if (!usage) {
      return null;
    }

    return (
      <div className="rounded-md border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-700">
        <span className="font-medium text-slate-800">{label}</span>
        <span className="ml-2">input {usage.input}</span>
        <span className="ml-2">cached {usage.cached}</span>
        <span className="ml-2">output {usage.output}</span>
      </div>
    );
  };

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h2 className="text-sm font-medium text-gray-900">
            面试结果：{candidate.name} - {position.title}
          </h2>
          {/* Completion status */}
          {isCompleted && (
            <span className="text-xs bg-green-100 text-green-700 px-2 py-0.5 rounded">
              已完成
            </span>
          )}
          {/* Save status indicator */}
          <span className={`text-xs ${
            saveStatus === 'saved' ? 'text-green-600' :
            saveStatus === 'saving' ? 'text-yellow-600' :
            'text-gray-400'
          }`}>
            {saveStatus === 'saved' && '✓ 已保存'}
            {saveStatus === 'saving' && '...'}
            {saveStatus === 'unsaved' && '（未保存）'}
          </span>
        </div>

        <div className="flex gap-2">
          <Button
            variant="secondary"
            onClick={handleGenerateSummary}
            isLoading={aiLoading}
            disabled={!position.description || !preferredResumeText}
          >
            AI 生成总结
          </Button>
          {!isCompleted && (
            <Button onClick={handleComplete}>
              完成面试
            </Button>
          )}
        </div>
      </div>

      {hasPageLink && (
        <Card>
          <CardHeader>
            <h3 className="text-sm font-medium text-gray-700">候选人页面</h3>
          </CardHeader>
          <CardBody>
            <a
              href={candidate.candidateLink}
              target="_blank"
              rel="noreferrer"
              className="text-sm text-blue-600 hover:text-blue-800 break-all"
            >
              {candidate.candidateLink}
            </a>
          </CardBody>
        </Card>
      )}

      {renderUsage(summaryUsage, 'AI 总结生成 Token')}

      {/* Interview Info */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-medium text-gray-700">面试信息</h3>
        </CardHeader>
        <CardBody>
          <div className="grid grid-cols-3 gap-3">
            <Input
              label="面试官"
              value={result.interview_info.interviewer}
              onChange={(e) =>
                setResult({
                  ...result,
                  interview_info: { ...result.interview_info, interviewer: e.target.value },
                })
              }
            />
            <Input
              label="时间"
              value={result.interview_info.interview_time}
              onChange={(e) =>
                setResult({
                  ...result,
                  interview_info: { ...result.interview_info, interview_time: e.target.value },
                })
              }
            />
            <Select
              label="总体结果"
              value={result.interview_info.overall_result}
              onChange={(e) =>
                setResult({
                  ...result,
                  interview_info: {
                    ...result.interview_info,
                    overall_result: e.target.value as '通过' | '不通过' | '待定',
                  },
                })
              }
              options={resultOptions}
            />
          </div>
        </CardBody>
      </Card>

      {/* Evaluation Dimensions */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium text-gray-700">评估维度</h3>
            <Button variant="ghost" size="sm" onClick={addDimension}>
              + 添加维度
            </Button>
          </div>
        </CardHeader>
        <CardBody className="space-y-3">
          {result.evaluation_dimensions.map((dim, index) => (
            <EvaluationDimensionCard
              key={index}
              dimension={dim}
              onUpdate={(updates) => updateDimension(index, updates)}
              onRemove={() => removeDimension(index)}
              canRemove={result.evaluation_dimensions.length > 1}
            />
          ))}
        </CardBody>
      </Card>

      {/* Summary */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-medium text-gray-700">综合评价</h3>
        </CardHeader>
        <CardBody className="space-y-3">
          <div className="grid grid-cols-2 gap-3">
            <Input
              label="建议级别"
              value={result.summary.suggested_level}
              onChange={(e) =>
                setResult({
                  ...result,
                  summary: { ...result.summary, suggested_level: e.target.value },
                })
              }
              placeholder="例如：H7、P6"
            />
            <Select
              label="综合评分"
              value={result.summary.comprehensive_score.toString()}
              onChange={(e) =>
                setResult({
                  ...result,
                  summary: { ...result.summary, comprehensive_score: parseInt(e.target.value) },
                })
              }
              options={scoreOptions}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <Select
              label="面试结论"
              value={result.summary.interview_conclusion}
              onChange={(e) =>
                setResult({
                  ...result,
                  summary: {
                    ...result.summary,
                    interview_conclusion: e.target.value as '通过' | '不通过' | '待定',
                  },
                })
              }
              options={resultOptions}
            />
            <div className="flex items-center pt-6">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={result.summary.is_strongly_recommended}
                  onChange={(e) =>
                    setResult({
                      ...result,
                      summary: {
                        ...result.summary,
                        is_strongly_recommended: e.target.checked,
                      },
                    })
                  }
                  className="w-4 h-4 text-blue-600 rounded border-gray-300 focus:ring-blue-500"
                />
                <span className="text-sm text-gray-700">强烈推荐</span>
              </label>
            </div>
          </div>

          <Textarea
            label="总体评价"
            value={result.summary.overall_comment}
            onChange={(e) =>
              setResult({
                ...result,
                summary: { ...result.summary, overall_comment: e.target.value },
              })
            }
            autoResize
            placeholder="请输入对候选人的综合评价..."
          />
        </CardBody>
      </Card>

      {/* Additional Info */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-medium text-gray-700">补充信息（可选）</h3>
        </CardHeader>
        <CardBody className="space-y-3">
          <StringListInput
            label="优势"
            items={strengths}
            onChange={setStrengths}
          />
          <StringListInput
            label="顾虑"
            items={concerns}
            onChange={setConcerns}
          />
          <StringListInput
            label="后续跟进问题"
            items={followUps}
            onChange={setFollowUps}
          />
        </CardBody>
      </Card>

      {/* Export Buttons */}
      <Card>
        <CardBody className="flex justify-end gap-2">
          {!isCompleted && (
            <Button onClick={handleComplete}>
              完成面试
            </Button>
          )}
          <ExportButtons
            result={{
              ...result,
              additional_info: {
                strengths,
                concerns,
                follow_up_questions: followUps,
              },
            }}
            candidateName={candidate.name}
            positionTitle={position.title}
          />
        </CardBody>
      </Card>
    </div>
  );
};

// Helper component for string list input
const StringListInput: React.FC<{
  label: string;
  items: string[];
  onChange: (items: string[]) => void;
}> = ({ label, items, onChange }) => {
  const [newItem, setNewItem] = useState('');

  const handleAdd = () => {
    if (newItem.trim()) {
      onChange([...items, newItem.trim()]);
      setNewItem('');
    }
  };

  const handleRemove = (index: number) => {
    onChange(items.filter((_, i) => i !== index));
  };

  return (
    <div>
      <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>
      <div className="space-y-1">
        {items.map((item, index) => (
          <div key={index} className="flex items-center gap-2">
            <span className="text-sm text-gray-600">• {item}</span>
            <button
              onClick={() => handleRemove(index)}
              className="text-gray-400 hover:text-red-500"
            >
              <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        ))}
        <div className="flex gap-2">
          <Input
            value={newItem}
            onChange={(e) => setNewItem(e.target.value)}
            placeholder={`添加${label}...`}
            onKeyPress={(e) => e.key === 'Enter' && handleAdd()}
          />
          <Button variant="ghost" size="sm" onClick={handleAdd} disabled={!newItem.trim()}>
            添加
          </Button>
        </div>
      </div>
    </div>
  );
};
